import type { CalculatorKey } from './calculator.types'

export const calculatorKeys: readonly CalculatorKey[] = [
  {
    id: 'clear',
    label: 'C',
    kind: 'action',
    action: 'clear',
    ariaLabel: 'Clear expression',
  },
  {
    id: 'delete',
    label: '⌫',
    kind: 'action',
    action: 'delete',
    ariaLabel: 'Delete last character',
  },
  {
    id: 'left-parenthesis',
    label: '(',
    value: '(',
    kind: 'parenthesis',
    ariaLabel: 'Left parenthesis',
  },
  {
    id: 'right-parenthesis',
    label: ')',
    value: ')',
    kind: 'parenthesis',
    ariaLabel: 'Right parenthesis',
  },
  {
    id: 'square-root',
    label: '√',
    value: 'sqrt(',
    kind: 'function',
    ariaLabel: 'Square root',
  },
  {
    id: 'power',
    label: '^',
    value: '^',
    kind: 'operator',
    ariaLabel: 'Exponentiation',
  },
  {
    id: 'percentage',
    label: '%',
    value: '%',
    kind: 'percentage',
    ariaLabel: 'Percentage',
  },
  {
    id: 'divide',
    label: '÷',
    value: '/',
    kind: 'operator',
    ariaLabel: 'Divide',
  },
  {
    id: 'seven',
    label: '7',
    value: '7',
    kind: 'digit',
    ariaLabel: '7',
  },
  {
    id: 'eight',
    label: '8',
    value: '8',
    kind: 'digit',
    ariaLabel: '8',
  },
  {
    id: 'nine',
    label: '9',
    value: '9',
    kind: 'digit',
    ariaLabel: '9',
  },
  {
    id: 'multiply',
    label: '×',
    value: '*',
    kind: 'operator',
    ariaLabel: 'Multiply',
  },
  {
    id: 'four',
    label: '4',
    value: '4',
    kind: 'digit',
    ariaLabel: '4',
  },
  {
    id: 'five',
    label: '5',
    value: '5',
    kind: 'digit',
    ariaLabel: '5',
  },
  {
    id: 'six',
    label: '6',
    value: '6',
    kind: 'digit',
    ariaLabel: '6',
  },
  {
    id: 'subtract',
    label: '−',
    value: '-',
    kind: 'operator',
    ariaLabel: 'Subtract',
  },
  {
    id: 'one',
    label: '1',
    value: '1',
    kind: 'digit',
    ariaLabel: '1',
  },
  {
    id: 'two',
    label: '2',
    value: '2',
    kind: 'digit',
    ariaLabel: '2',
  },
  {
    id: 'three',
    label: '3',
    value: '3',
    kind: 'digit',
    ariaLabel: '3',
  },
  {
    id: 'add',
    label: '+',
    value: '+',
    kind: 'operator',
    ariaLabel: 'Add',
  },
  {
    id: 'zero',
    label: '0',
    value: '0',
    kind: 'digit',
    ariaLabel: '0',
    className: 'spanTwo',
  },
  {
    id: 'decimal',
    label: '.',
    value: '.',
    kind: 'decimal',
    ariaLabel: 'Decimal point',
  },
  {
    id: 'evaluate',
    label: '=',
    kind: 'action',
    action: 'evaluate',
    ariaLabel: 'Evaluate expression',
  },
]
